### ISSUE TITLE
setup instructions dont work for pip route

### ISSUE THREAD

**Issue by Prady04** [legout/yahoo-symbols#1]
pip install git+https://github.com/legout/yahoo-symbols.git
Collecting git+https://github.com/legout/yahoo-symbols.git
  Cloning https://github.com/legout/yahoo-symbols.git to c:\users\prade\appdata\local\temp\pip-req-build-rwx6_ukn
  Running command git clone --filter=blob:none --quiet https://github.com/legout/yahoo-symbols.git 'C:\Users\prade\AppData\Local\Temp\pip-req-build-rwx6_ukn'
  Resolved https://github.com/legout/yahoo-symbols.git to commit a0236c8d3b70c99e208ff96aa698088271dac4a0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pydala2@ git+https://github.com/legout/pydala2 (from yahoo-symbols==0.1.2)
  Cloning https://github.com/legout/pydala2 to c:\users\prade\appdata\local\temp\pip-install-za3oj7cv\pydala2_2d7bd3bff413469089de0c5114424e00
  Running command git clone --filter=blob:none --quiet https://github.com/legout/pydala2 'C:\Users\prade\AppData\Local\Temp\pip-install-za3oj7cv\pydala2_2d7bd3bff413469089de0c5114424e00'
  Resolved https://github.com/legout/pydala2 to commit fd018427c9b3db73ec27654d1024352e36e585e3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting yfin@ git+https://github.com/legout/yfin (from yahoo-symbols==0.1.2)
  Cloning https://github.com/legout/yfin to c:\users\prade\appdata\local\temp\pip-install-za3oj7cv\yfin_996f9fc3a4694a48a646e121281888cc
  Running command git clone --filter=blob:none --quiet https://github.com/legout/yfin 'C:\Users\prade\AppData\Local\Temp\pip-install-za3oj7cv\yfin_996f9fc3a4694a48a646e121281888cc'
  Resolved https://github.com/legout/yfin to commit 7fe2dfc2059766385e151f63b9eae7399e41b1ef
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting msgspec>=0.18.4 (from yahoo-symbols==0.1.2)
  Downloading msgspec-0.18.4-cp311-cp311-win_amd64.whl (177 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.3/177.3 kB 3.6 MB/s eta 0:00:00
Collecting typer>=0.9.0 (from yahoo-symbols==0.1.2)
  Downloading typer-0.9.0-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.9/45.9 kB 2.4 MB/s eta 0:00:00
Collecting rich>=13.6.0 (from yahoo-symbols==0.1.2)
  Using cached rich-13.6.0-py3-none-any.whl (239 kB)
Collecting rocketry>=2.5.1 (from yahoo-symbols==0.1.2)
  Downloading rocketry-2.5.1-py3-none-any.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.7/216.7 kB 4.4 MB/s eta 0:00:00
Collecting polars[sqlalchemy]>=0.19.12 (from yahoo-symbols==0.1.2)
  Downloading polars-0.19.12-cp38-abi3-win_amd64.whl (24.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 4.0 MB/s eta 0:00:00
Collecting pydantic==1.10.10 (from yahoo-symbols==0.1.2)
  Downloading pydantic-1.10.10-cp311-cp311-win_amd64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 7.4 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.2.0 in c:\python\flexstart\flxv\lib\site-packages (from pydantic==1.10.10->yahoo-symbols==0.1.2) (4.5.0)
Requirement already satisfied: sqlalchemy in c:\python\flexstart\flxv\lib\site-packages (from polars[sqlalchemy]>=0.19.12->yahoo-symbols==0.1.2) (2.0.7)
Requirement already satisfied: pandas in c:\python\flexstart\flxv\lib\site-packages (from polars[sqlalchemy]>=0.19.12->yahoo-symbols==0.1.2) (2.0.2)
Collecting markdown-it-py>=2.2.0 (from rich>=13.6.0->yahoo-symbols==0.1.2)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\python\flexstart\flxv\lib\site-packages (from rich>=13.6.0->yahoo-symbols==0.1.2) (2.15.1)
Requirement already satisfied: python-dateutil in c:\python\flexstart\flxv\lib\site-packages (from rocketry>=2.5.1->yahoo-symbols==0.1.2) (2.8.2)
Collecting redbird>=0.5.0 (from rocketry>=2.5.1->yahoo-symbols==0.1.2)
  Downloading redbird-0.7.1-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\python\flexstart\flxv\lib\site-packages (from typer>=0.9.0->yahoo-symbols==0.1.2) (8.1.3)
Collecting pyarrow>=12.0.1 (from pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading pyarrow-14.0.0-cp311-cp311-win_amd64.whl (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 7.4 MB/s eta 0:00:00
Collecting s3fs>=2023.6.0 (from pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading s3fs-2023.10.0-py3-none-any.whl (28 kB)
Collecting duckdb>=0.9.1 (from pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading duckdb-0.9.1-cp311-cp311-win_amd64.whl (10.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 1.7 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.65.0 in c:\python\flexstart\flxv\lib\site-packages (from pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2) (4.65.0)
Collecting joblib>=1.3.2 (from pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 6.2 MB/s eta 0:00:00
Collecting pandas (from polars[sqlalchemy]>=0.19.12->yahoo-symbols==0.1.2)
  Downloading pandas-2.1.2-cp311-cp311-win_amd64.whl (10.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 7.4 MB/s eta 0:00:00
Collecting pendulum>=2.1.2 (from pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Using cached pendulum-2.1.2-cp311-cp311-win_amd64.whl
Collecting parallel-requests@ git+https://github.com/legout/parallel-requests (from yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2)
  Cloning https://github.com/legout/parallel-requests to c:\users\prade\appdata\local\temp\pip-install-za3oj7cv\parallel-requests_cc670cb84b364f95822e018ec5ef1832
  Running command git clone --filter=blob:none --quiet https://github.com/legout/parallel-requests 'C:\Users\prade\AppData\Local\Temp\pip-install-za3oj7cv\parallel-requests_cc670cb84b364f95822e018ec5ef1832'
  Resolved https://github.com/legout/parallel-requests to commit 57c2ddb5a3c1d61ce0e2ca6f856eec965a481494
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.24.2 in c:\python\flexstart\flxv\lib\site-packages (from yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (1.24.2)
Requirement already satisfied: requests>=2.28.1 in c:\python\flexstart\flxv\lib\site-packages (from yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (2.28.2)
Requirement already satisfied: lxml>=4.9.1 in c:\python\flexstart\flxv\lib\site-packages (from yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (4.9.2)
Requirement already satisfied: colorama in c:\python\flexstart\flxv\lib\site-packages (from click<9.0.0,>=7.1.1->typer>=0.9.0->yahoo-symbols==0.1.2) (0.4.6)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.6.0->yahoo-symbols==0.1.2)
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: pytz>=2020.1 in c:\python\flexstart\flxv\lib\site-packages (from pandas->polars[sqlalchemy]>=0.19.12->yahoo-symbols==0.1.2) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\python\flexstart\flxv\lib\site-packages (from pandas->polars[sqlalchemy]>=0.19.12->yahoo-symbols==0.1.2) (2023.3)
Collecting pytzdata>=2020.1 (from pendulum>=2.1.2->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 490.0/490.0 kB 7.6 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\python\flexstart\flxv\lib\site-packages (from python-dateutil->rocketry>=2.5.1->yahoo-symbols==0.1.2) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python\flexstart\flxv\lib\site-packages (from requests>=2.28.1->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python\flexstart\flxv\lib\site-packages (from requests>=2.28.1->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\flexstart\flxv\lib\site-packages (from requests>=2.28.1->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\flexstart\flxv\lib\site-packages (from requests>=2.28.1->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (2022.12.7)
Collecting aiobotocore~=2.7.0 (from s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading aiobotocore-2.7.0-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB ? eta 0:00:00
Collecting fsspec==2023.10.0 (from s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading fsspec-2023.10.0-py3-none-any.whl (166 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.4/166.4 kB 9.8 MB/s eta 0:00:00
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\python\flexstart\flxv\lib\site-packages (from s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2) (3.8.4)  
Requirement already satisfied: asyncio>=3.4.3 in c:\python\flexstart\flxv\lib\site-packages (from parallel-requests@ git+https://github.com/legout/parallel-requests->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (3.4.3)
Requirement already satisfied: python-dotenv>=1.0.0 in c:\python\flexstart\flxv\lib\site-packages (from parallel-requests@ git+https://github.com/legout/parallel-requests->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (1.0.0)
Requirement already satisfied: asyncer>=0.0.2 in c:\python\flexstart\flxv\lib\site-packages (from parallel-requests@ git+https://github.com/legout/parallel-requests->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (0.0.2)
Requirement already satisfied: loguru>=0.6.0 in c:\python\flexstart\flxv\lib\site-packages (from parallel-requests@ git+https://github.com/legout/parallel-requests->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (0.6.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\python\flexstart\flxv\lib\site-packages (from sqlalchemy->polars[sqlalchemy]>=0.19.12->yahoo-symbols==0.1.2) (2.0.2)
Collecting botocore<1.31.65,>=1.31.16 (from aiobotocore~=2.7.0->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading botocore-1.31.64-py3-none-any.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 7.3 MB/s eta 0:00:00
Collecting wrapt<2.0.0,>=1.10.10 (from aiobotocore~=2.7.0->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Using cached wrapt-1.15.0-cp311-cp311-win_amd64.whl (36 kB)
Collecting aioitertools<1.0.0,>=0.5.1 (from aiobotocore~=2.7.0->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading aioitertools-0.11.0-py3-none-any.whl (23 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\python\flexstart\flxv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\python\flexstart\flxv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\python\flexstart\flxv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\python\flexstart\flxv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\python\flexstart\flxv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\python\flexstart\flxv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2) (1.3.1)
Requirement already satisfied: anyio<4.0.0,>=3.4.0 in c:\python\flexstart\flxv\lib\site-packages (from asyncer>=0.0.2->parallel-requests@ git+https://github.com/legout/parallel-requests->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (3.7.0)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\python\flexstart\flxv\lib\site-packages (from loguru>=0.6.0->parallel-requests@ git+https://github.com/legout/parallel-requests->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (1.1.0)
Requirement already satisfied: sniffio>=1.1 in c:\python\flexstart\flxv\lib\site-packages (from anyio<4.0.0,>=3.4.0->asyncer>=0.0.2->parallel-requests@ git+https://github.com/legout/parallel-requests->yfin@ git+https://github.com/legout/yfin->yahoo-symbols==0.1.2) (1.3.0)
Collecting jmespath<2.0.0,>=0.7.1 (from botocore<1.31.65,>=1.31.16->aiobotocore~=2.7.0->s3fs>=2023.6.0->pydala2@ git+https://github.com/legout/pydala2->yahoo-symbols==0.1.2)
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Building wheels for collected packages: yahoo-symbols, pydala2, yfin, parallel-requests
  Building wheel for yahoo-symbols (pyproject.toml) ... done
  Created wheel for yahoo-symbols: filename=yahoo_symbols-0.1.2-py3-none-any.whl size=6394 sha256=456f65b6a832e6ee70d77ae3694f16a74357c105dbbabd95cb202e2ab89b33a8
  Stored in directory: C:\Users\prade\AppData\Local\Temp\pip-ephem-wheel-cache-t_ag8vre\wheels\6c\f1\4f\8ec15ac7db17100d48c689c836552f9017222a538d0e64f0c2
  Building wheel for pydala2 (pyproject.toml) ... done
  Created wheel for pydala2: filename=pydala2-0.2-py3-none-any.whl size=32628 sha256=9ce7eda2d01dd29cc3c32a5333d24f1a2cd490a7115eafbb0a591b8924a1198a
  Stored in directory: C:\Users\prade\AppData\Local\Temp\pip-ephem-wheel-cache-t_ag8vre\wheels\a7\e7\5a\4b8beb9b749da7fbd2c9af3eaf3310b85fb75aaca2953ca6f2
  Building wheel for yfin (pyproject.toml) ... done
  Created wheel for yfin: filename=yfin-0.2.4-py3-none-any.whl size=22990 sha256=32c5160e5f2fd15200ba363e9c0e831dc9a81a92cf721a39bbb8902d1455bc95
  Stored in directory: C:\Users\prade\AppData\Local\Temp\pip-ephem-wheel-cache-t_ag8vre\wheels\8d\ba\d8\89a44c8bc1702b11eda96fe280759ca2bb3780afcc616af479
  Building wheel for parallel-requests (pyproject.toml) ... done
  Created wheel for parallel-requests: filename=parallel_requests-0.2.4-py3-none-any.whl size=16053 sha256=e25b9a26580c7cbc5bc358f837fdeeadb45eabe59652f5cbf968a33c8fd90fef
  Stored in directory: C:\Users\prade\AppData\Local\Temp\pip-ephem-wheel-cache-t_ag8vre\wheels\fa\ec\69\0aec44d61e2bb341d22b1fad8e70e599055c08834826eb0eaf
Successfully built yahoo-symbols pydala2 yfin parallel-requests
Installing collected packages: wrapt, pytzdata, pydantic, pyarrow, polars, msgspec, mdurl, joblib, jmespath, fsspec, duckdb, aioitertools, typer, redbird, pendulum, pandas, markdown-it-py, botocore, rocketry, rich, parallel-requests, aiobotocore, yfin, s3fs, pydala2, yahoo-symbols
ttempting uninstall: pandas
    Found existing installation: pandas 2.0.2
    Uninstalling pandas-2.0.2:
      Successfully uninstalled pandas-2.0.2
Successfully installed aiobotocore-2.7.0 aioitertools-0.11.0 botocore-1.31.64 duckdb-0.9.1 fsspec-2023.10.0 jmespath-1.0.1 joblib-1.3.2 markdown-it-py-3.0.0 mdurl-0.1.2 msgspec-0.18.4 pandas-2.1.2 parallel-requests-0.2.4 pendulum-2.1.2 polars-0.19.12 pyarrow-14.0.0 pydala2-0.2 pydantic-1.10.10 pytzdata-2020.1 redbird-0.7.1 rich-13.6.0 rocketry-2.5.1 s3fs-2023.10.0 typer-0.9.0 wrapt-1.15.0 yahoo-symbols-0.1.2 yfin-0.2.4
[1. Run the script manually.](https://github.com/legout/yahoo-symbols#1-run-the-script-manually)
python -m yahoo_symbols.run --query-length=2 --types=equity,etf

(flxv) PS C:\Python\FlexStart> python -m yahoo_symbols.run --query-length=2 --types=equity,etf --storage-type sqlite   
C:\Python\FlexStart\flxv\Scripts\python.exe: Error while finding module specification for 'yahoo_symbols.run' (ModuleNotFoundError: No module named 'yahoo_symbols')

**Comment by legout** [comment]
Fixed
