### ISSUE TITLE
download doesnt work for sqlite

### ISSUE THREAD

**Issue by Prady04** [legout/yahoo-symbols#2]
command used python .\yahoo-symbols\yahoo_symbols\run.py download  "india" --storage-type=sqlite equity,etf 

 concurrency = 10                                                                 │ │
│ │                   debug = False                                                              │ │
│ │          lookup_queries = ['india']                                                          │ │
│ │                  lu_res = shape: (822, 4)                                                    │ │
│ │                           ┌──────────────┬──────────┬───────────────────────────────┬──────… │ │
│ │                           │ symbol       ┆ exchange ┆ name                          ┆ type   │ │
│ │                           │                                                                  │ │
│ │                           │ ---          ┆ ---      ┆ ---                           ┆ ---    │ │
│ │                           │                                                                  │ │
│ │                           │ str          ┆ str      ┆ str                           ┆ str    │ │
│ │                           │                                                                  │ │
│ │                           ╞══════════════╪══════════╪═══════════════════════════════╪══════… │ │
│ │                           │ INDI         ┆ NCM      ┆ indie Semiconductor, Inc.     ┆ equity │ │
│ │                           │                                                                  │ │
│ │                           │ INDY         ┆ NGM      ┆ iShares India 50 ETF          ┆ etf    │ │
│ │                           │                                                                  │ │
│ │                           │ FLIN         ┆ PCX      ┆ Franklin FTSE India ETF       ┆ etf    │ │
│ │                           │                                                                  │ │
│ │                           │ UNIONBANK.NS ┆ NSI      ┆ UNION BK OF INDIA             ┆ equity │ │
│ │                           │                                                                  │ │
│ │                           │ …            ┆ …        ┆ …                             ┆ …      │ │
│ │                           │                                                                  │ │
│ │                           │ JYJ4.MU      ┆ MUN      ┆ JPM-INDIA FD JPMI DADL        ┆ etf    │ │
│ │                           │                                                                  │ │
│ │                           │ FLXID.XC     ┆ CXE      ┆ Franklin FTSE India UCITS ETF ┆ etf    │ │
│ │                           │                                                                  │ │
│ │                           │ NDIAA.XC     ┆ CXE      ┆ iShares MSCI India UCITS ETF  ┆ etf    │ │
│ │                           │                                                                  │ │
│ │                           │ FJRP.HA      ┆ HAN      ┆ FID.FDS-INDIA FOC.FD A EO     ┆ etf    │ │
│ │                           │                                                                  │ │
│ │                           └──────────────┴──────────┴───────────────────────────────┴──────… │ │
│ │             max_retries = 5                                                                  │ │
│ │ random_delay_multiplier = 10                                                                 │ │
│ │            random_proxy = False                                                              │ │
│ │       random_user_agent = True                                                               │ │
│ │               s3_bucket = None                                                               │ │
│ │              s3_profile = 'default'                                                          │ │
│ │            storage_path = 'yahoo-symbols'                                                    │ │
│ │            storage_type = 'sqlite'                                                           │ │
│ │                 symbols = [                                                                  │ │
│ │                           │   '01D5.BE',                                                     │ │
│ │                           │   '01D6.BE',                                                     │ │
│ │                           │   '08GPG.BO',                                                    │ │
│ │                           │   '08MPD.BO',                                                    │ │
│ │                           │   '0I7M.BE',                                                     │ │
│ │                           │   '0I7M.MU',                                                     │ │
│ │                           │   '0JK5.L',                                                      │ │
│ │                           │   '0JKV.L',                                                      │ │
│ │                           │   '0MRA.IL',                                                     │ │
│ │                           │   '11AGG.BO',                                                    │ │
│ │                           │   ... +812                                                       │ │
│ │                           ]                                                                  │ │
│ │                   type_ = 'equity,etf'                                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Python\FlexStart\flxv\yahoo-symbols\yahoo_symbols\helpers.py:62 in get_new_symbols            │
│                                                                                                  │
│    59 │   s3_bucket: str,                                                                        │
│    60 ):                                                                                         │
│    61 │   if "sqlite" in storage_type:                                                           │
│ ❱  62 │   │   existing_symbols = run_sqlite_query(                                               │
│    63 │   │   │   f"SELECT DISTINCT symbol FROM {type_}", storage_path=storage_path              │
│    64 │   │   )                                                                                  │
│    65 │   │   if existing_symbols is not None:                                                   │
│                                                                                                  │
│ ╭──────────── locals ────────────╮                                                               │
│ │    s3_bucket = None            │                                                               │
│ │   s3_profile = 'default'       │                                                               │
│ │ storage_path = 'yahoo-symbols' │                                                               │
│ │ storage_type = 'sqlite'        │                                                               │
│ │      symbols = [               │                                                               │
│ │                │   '01D5.BE',  │                                                               │
│ │                │   '01D6.BE',  │                                                               │
│ │                │   '08GPG.BO', │                                                               │
│ │                │   '08MPD.BO', │                                                               │
│ │                │   '0I7M.BE',  │                                                               │
│ │                │   '0I7M.MU',  │                                                               │
│ │                │   '0JK5.L',   │                                                               │
│ │                │   '0JKV.L',   │                                                               │
│ │                │   '0MRA.IL',  │                                                               │
│ │                │   '11AGG.BO', │                                                               │
│ │                │   ... +812    │                                                               │
│ │                ]               │                                                               │
│ │        type_ = 'equity,etf'    │                                                               │
│ ╰────────────────────────────────╯                                                               │
│                                                                                                  │
│ C:\Python\FlexStart\flxv\yahoo-symbols\yahoo_symbols\helpers.py:45 in run_sqlite_query           │
│                                                                                                  │
│    42 │   │   │   os.makedirs(storage_path, exist_ok=True)                                       │
│    43 │   │   │   storage_path = os.path.join(storage_path, "yahoo-symbols.sqlite")              │
│    44 │                                                                                          │
│ ❱  45 │   con = sqlite3.connect(f"sqlite3:///{storage_path}")                                    │
│    46 │                                                                                          │
│    47 │   # check table exists                                                                   │
│    48 │   table_name = re.findall(r"(?i)FROM\s+([\w]+\b)", sql)[0]                               │
│                                                                                                  │
│ ╭──────────────────────── locals ─────────────────────────╮                                      │
│ │          sql = 'SELECT DISTINCT symbol FROM equity,etf' │                                      │
│ │ storage_path = 'yahoo-symbols\\yahoo-symbols.sqlite'

**Comment by legout** [comment]
Fixed.
